version: "3.9"
networks:
  neo4j-internal:

services:

  neo4j-server1:
    # Docker image to be used
    image: neo4j:5.3.0

    # Hostname
    hostname: server1

    # Service-level network, which specifies the networks, from the list of the top-level networks (in this case only neo4j-internal), that the server will connect to.
    # Adds a network alias (used in neo4j.conf when configuring the discovery members)
    networks:
      neo4j-internal:
        aliases:
          - neo4j-network
    # The ports that will be accessible from outside the container - HTTP (7474) and Bolt (7687).
    ports:
      - "7474:7474"
      - "7687:7687"
#  api:
#    build: api
#    ports:
#      - "8000:5000"