version: "3"

services:

  # Neo4j database
  neo4j:
    image: neo4j:5.3.0
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/12345678

  # Python code import the MovieLens dataset into Neo4j
  import:
    build: import
    depends_on:
      - neo4j
    restart: on-failure
    links:
      - neo4j
    environment:
      NEO4J_HOST: neo4j

  # API
  api:
    build: api
    ports:
      - 5000:5000
    depends_on:
      - neo4j
    restart: on-failure
    links:
      - neo4j
    environment:
      NEO4J_HOST: neo4j